import { supabaseServer } from "@/lib/supabase/server";
import { supabaseAdmin } from "@/lib/supabase/admin";

export async function listClients() {
  const supabase = await supabaseServer();

  const {
    data: { user },
    error: userErr,
  } = await supabase.auth.getUser();

  if (userErr || !user) throw new Error("Not authenticated");

  const { data, error } = await supabase
    .from("clients")
    .select("id,name,email,active,portal_enabled,public_token,created_at,updated_at")
    .order("created_at", { ascending: false });

  if (error) throw error;
  return data ?? [];
}

export async function createClient(input: {
  name: string;
  email?: string | null;
  phone_number?: string | null;
}) {
  const supabase = await supabaseServer();

  const {
    data: { user },
    error: userErr,
  } = await supabase.auth.getUser();

  if (userErr || !user) throw new Error("Not authenticated");

  const { data, error } = await supabase
    .from("clients")
    .insert({
      user_id: user.id,
      name: input.name.trim(),
      email: input.email?.trim() || null,
      phone_number: input.phone_number?.trim() || null,
      // public_token generated by DB default
    })
    .select("id")
    .single();

  if (error) throw error;
  if (!data) throw new Error("Insert succeeded but no row returned");

  return data; // ✅ fixes “void” return
}

export async function getClient(clientId: string) {
  const supabase = await supabaseServer();

  const { data, error } = await supabase
    .from("clients")
    .select(
      "id,name,email,phone_number,active,portal_enabled,public_token,notify_by_email,created_at,updated_at"
    )
    .eq("id", clientId)
    .single();

  if (error) throw error;
  return data;
}

export async function createClientAsDevOwner(input: {
  name: string;
  email?: string | null;
  phone_number?: string | null;
}) {
  const ownerId = process.env.DEV_OWNER_USER_ID;
  if (!ownerId) throw new Error("Missing DEV_OWNER_USER_ID");

  const supabase = supabaseAdmin();

  const { data, error } = await supabase
    .from("clients")
    .insert({
      user_id: ownerId,
      name: input.name.trim(),
      email: input.email?.trim() || null,
      phone_number: input.phone_number?.trim() || null,
    })
    .select("id") // ensure id is returned
    .maybeSingle(); // slightly safer than single() during weird responses

  if (error) throw error;
  if (!data?.id) throw new Error("Insert succeeded but no id returned");

  return data; // { id }
}

export async function listClientsAsDevOwner() {
  const ownerId = process.env.DEV_OWNER_USER_ID;
  if (!ownerId) throw new Error("Missing DEV_OWNER_USER_ID");

  const supabase = supabaseAdmin();

  const { data, error } = await supabase
    .from("clients")
    .select("id,name,email,active,portal_enabled,public_token,created_at,updated_at")
    .eq("user_id", ownerId)
    .order("created_at", { ascending: false });

  if (error) throw error;
  return data ?? [];
}

export async function getClientAsDevOwner(clientId: string) {
  const ownerId = process.env.DEV_OWNER_USER_ID;
  if (!ownerId) throw new Error("Missing DEV_OWNER_USER_ID");

  if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(clientId)) {
    throw new Error(`Invalid clientId (expected uuid): "${clientId}"`);
  }

  const supabase = supabaseAdmin();

  const { data, error } = await supabase
    .from("clients")
    .select(
      "id,name,email,phone_number,active,portal_enabled,public_token,notify_by_email,created_at,updated_at"
    )
    .eq("id", clientId)
    .eq("user_id", ownerId) // safety filter
    .single();

  if (error) throw error;
  if (!data) throw new Error("Client not found");
  return data;
}
